Remove Redux from dataset detail page
Amsterdam/atlas pull request #3400
Opened 2020-10-08 07:35 UTC by jonkoops

2020-10-10 10:59 UTC, chrisvanmook requested changes

2020-10-10 10:59 UTC, chrisvanmook commented on src/app/utils/joinUrl.ts
> +export default function joinUrl(paths: string[], trailing = false) {
why false by default?

2020-10-10 10:59 UTC, chrisvanmook commented on src/root-saga.js
> -    fork(watchFetchDatasets),
awww yeah 🎉

2020-10-10 10:59 UTC, chrisvanmook commented on src/shared/services/date-formatter/date-formatter.js
> +    ...(month && { month: 'long' }),
On the detail pages we sometimes use '2-digits' or just numeric. Think we have 2 options here:
- Make this configurable by passing the options instead of day, month, year (`Intl.DateTimeFormatOptions`) 
- Perhaps we should not use this util and stay close to vanilla JS. IMHO this util only exists because we don't have TS everywhere yet

2020-10-12 06:28 UTC, janjaap requested changes
A couple of remarks; the semantic issues in the `DatasetDetailPage` component are IMO blocking.

2020-10-12 06:28 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function kebabCase(input: string) {
No need to set the type of the return value?

2020-10-12 06:28 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function getOptionLabel(id: string, options: DatasetFilterOption[]) {
This function seems to return either an object or a string; wouldn't it be better to set the type of the return value as well?

2020-10-12 06:28 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function getFileSize(bytes: number) {
What is the reason for changing `const` into `function`? None of the functions in this component are using references to `this`, so there should be no need to change the function from anonymous to named.

2020-10-12 06:28 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +  const startDate = period['time:hasBeginning'] ? new Date(period['time:hasBeginning']) : null
Couldn't 
```javascript
new Date(period?.['time:hasBeginning']) ?? null
``` 
also be used here? The `Date` constructor should return `undefined` for an invalid constructor param.

2020-10-12 06:28 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +  slug: string
`slug` Doesn't seem to be used

2020-10-12 06:28 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +                  <h2 className="o-header__title u-margin__bottom--3 ">{dataset['dct:title']}</h2>
This is not a valid HTML document structure; the `h2` should come before the `h3`. Looking at the element order in the page, the `h3` should not be a heading element, the `h2` should be an `h1`, the `h3`s should be `h2` and `h4` should be `h3`.

2020-10-12 09:45 UTC, jonkoops commented on src/app/utils/joinUrl.ts
> +export default function joinUrl(paths: string[], trailing = false) {
Most APIs want to end on a non-trailing slash, for example `datasets/1234` so it makes sense not to include it by default.

2020-10-12 09:48 UTC, janjaap commented on src/app/utils/joinUrl.ts
> +export default function joinUrl(paths: string[], trailing = false) {
I think that the general rule of thumb is that list endpoints end with a slash and detail endpoints do not. Not sure if that rule is written in stone, tho.

2020-10-12 09:48 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function kebabCase(input: string) {
In this case TypeScript can infer the return type based on the value we return, which is always a string.

2020-10-12 09:51 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function getOptionLabel(id: string, options: DatasetFilterOption[]) {
As far as I can tell this method will always return a string, see the inferred type:

![image](https://user-images.githubusercontent.com/695720/95732620-44d42380-0c81-11eb-859d-8bee6202ba3a.png)

2020-10-12 09:54 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function getFileSize(bytes: number) {
No particular reason, in this case the method does not immediately return a value so I don't see a benefit in using an arrow function.

2020-10-12 09:57 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +  const startDate = period['time:hasBeginning'] ? new Date(period['time:hasBeginning']) : null
Running `new Date(undefined)` in my console (see below) I am getting back a constructed Date object which holds an invalid date. So unless I am missing something here I do not think this is possible.

![image](https://user-images.githubusercontent.com/695720/95733196-0db24200-0c82-11eb-9ed2-47d1b1e81e94.png)

2020-10-12 09:58 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +  slug: string
Yeah, it's not used but it does exist here so I decided to add the type anyways. This will get compiled away in the final bundle as the types are eliminated.

2020-10-12 10:00 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function getFileSize(bytes: number) {
Is that a rule; that far arrow functions should return a value?

2020-10-12 10:00 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +  const startDate = period['time:hasBeginning'] ? new Date(period['time:hasBeginning']) : null
You're right; I was mistaken.

2020-10-12 10:17 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +                  <h2 className="o-header__title u-margin__bottom--3 ">{dataset['dct:title']}</h2>
Agreed, I fixed up the headings. I kept the 'subtitle' as a heading element as it is the heading for the text below it.

2020-10-12 11:12 UTC, jonkoops commented on src/shared/services/date-formatter/date-formatter.js
> +    ...(month && { month: 'long' }),
Yeah, agreed. I've cleaned up the utility and related code and tests.

2020-10-12 11:16 UTC, jonkoops commented on src/app/utils/joinUrl.ts
> +export default function joinUrl(paths: string[], trailing = false) {
Some list endpoints also do not end with a slash, it's a bit of a mess for sure.

2020-10-12 11:16 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function getFileSize(bytes: number) {
As in a linting rule? Not at this moment no. As far as I know we have no rules on this.

2020-10-12 11:30 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function getFileSize(bytes: number) {
Not necessarily a linting rule, more like a team agreement.

2020-10-12 11:32 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +function getFileSize(bytes: number) {
Not at this time, hopefully something we can agree on once we have space to fix up our linting.

2020-10-12 11:36 UTC, janjaap commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +                  <h1 className="o-header__title u-margin__top--0 u-margin__bottom--1">
This changes the structure of the document; it's semantically valid, but now the text `Dataset` will be displayed below the `h1`, where it was placed above that element before.

2020-10-12 11:38 UTC, jonkoops commented on src/app/pages/DatasetDetailPage/DatasetDetailPage.tsx
> +                  <h1 className="o-header__title u-margin__top--0 u-margin__bottom--1">
Yeah, I checked this. We're not using it on any other page so in this case it is fine.

2020-10-12 11:41 UTC, janjaap approved these changes

2020-10-12 11:42 UTC, janjaap commented on package.json
> +    "lodash.throttle": "^4.1.1",
Wasn't this package removed in a previous PR?

2020-10-12 12:33 UTC, jonkoops commented on package.json
> +    "lodash.throttle": "^4.1.1",
Good catch, must have missed it during the merge. Removed.

2020-10-12 12:37 UTC, chrisvanmook approved these changes

2020-10-12 12:57 UTC, merged