[DI-1154] Link to addresses from search results
Amsterdam/atlas pull request #3405
Opened 2020-10-09 07:13 UTC by janjaap

This PR fixes an issue where certain query parameters weren't persisted to the state. The bug was introduced in https://github.com/Amsterdam/atlas/pull/3305 with the removal of the `query` property from the search page state. Some of the changes of said PR are reverted in this PR which makes the functionality work again.

2020-10-09 08:04 UTC, chrisvanmook reviewed
I was actually hoping we could get rid of query's attached to `queryParameters.js` by using our new `useParam` hook. But perhaps we do have to wait until we can remove redux-first-router as this will cause issues when using together...

2020-10-09 08:11 UTC, janjaap commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +  const totalCount = results.length ? results.reduce((acc: number, { count }) => acc + count, 0) : 0
It is, yes. I changed it.

2020-10-09 10:24 UTC, jonkoops requested changes

2020-10-09 10:24 UTC, jonkoops commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +  endpoint: String
It's better to use the lower-case `string` here to refer to the primitive type of string rather than the constructor type. For more information see the TypeScript [documentation](https://www.typescriptlang.org/docs/handbook/basic-types.html#about-number-string-boolean-symbol-and-object).

2020-10-09 10:24 UTC, jonkoops commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +  const totalCount = results.length ? results.reduce((acc, { count }) => acc + count, 0) : 0
Nice cleanup! I think it could actually be reduced even more by removing the ternary entirely since a `reduce` on an empty array is a no-op. 

```suggestion
  const totalCount = results.reduce((acc, { count }) => acc + count, 0) 
```

2020-10-09 10:24 UTC, jonkoops commented on src/app/pages/SearchPage/SearchPageDucks.ts
> +export const getQuery = ({ [REDUCER_KEY]: { query } }: StoreValue) => query?.toString()
There is no need to use optional chaining here as the `SearchPageState` guarantees that `query` is always present and of type `string`.  If this is not the case the code that sets this value should be changed.

```suggestion
export const getQuery = ({ [REDUCER_KEY]: { query } }: StoreValue) => query
```

2020-10-09 10:24 UTC, jonkoops commented on src/store/params-registry/paramRegistry.js
> -    // Temporary fix to allow new params (using the useParam hook)
I don't have a clear indication if removing this code will break anything. @chrisvanmook perhaps you can judge this this better.

2020-10-09 10:24 UTC, jonkoops commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +type SingleResult = {
Personally I prefer to use `interface` over `type` in these cases as combining types can become messy very quickly especially in error messages from the TypeScript compiler. However we have been mixing these in the project already and since we don't have any linting in place the point is moot.

2020-10-09 10:24 UTC, jonkoops commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +  results: Array<DataSearchResults>
An alternative syntax you could use for arrays is `DataSearchResults[]`, but both are equally valid.

2020-10-12 06:36 UTC, janjaap commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +  const totalCount = results.length ? results.reduce((acc, { count }) => acc + count, 0) : 0
Could do that, but it will break when `results` is anything but an array.

2020-10-12 06:54 UTC, janjaap commented on src/store/params-registry/paramRegistry.js
> -    // Temporary fix to allow new params (using the useParam hook)
This particular change reverts a previous change by @chrisvanmook

2020-10-12 08:57 UTC, jonkoops commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +  const totalCount = results.length ? results.reduce((acc, { count }) => acc + count, 0) : 0
In this case we're relying on TypeScript to guarantee that this value is never anything else than an array (see the `DataSearchResults` interface). So checking it again here at runtime is not needed, unless of course the response can contain other values. In that case the type should be updated to reflect that.

2020-10-12 08:59 UTC, jonkoops commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +interface SingleResult {
Perhaps ` DataResult` would be be a more appropriate name, like the `__typename` from GQL.

2020-10-12 08:59 UTC, jonkoops commented on src/app/pages/SearchPage/DataSearchResults.tsx
> +interface DataSearchResults {
Perhaps ` CombinedDataResult` would be be a more appropriate name, like the `__typename` from GQL.

2020-10-12 09:03 UTC, jonkoops approved these changes
Looks good to me if @chrisvanmook can give his judgement as well.

2020-10-13 07:49 UTC, merged