Major Refactor: Moved detail pages from angularJS to React.
Amsterdam/atlas pull request #3428
Opened 2020-10-12 17:35 UTC by chrisvanmook

2020-10-14 11:39 UTC, janjaap commented on src/app/pages/DataDetailPage/DataDetailPage.tsx
> +            {!!result?.value?.data?.infoBox && <DetailInfoBox {...result?.value?.data?.infoBox} />}
Why is the double bang necessary here?

2020-10-14 11:39 UTC, janjaap commented on src/app/pages/DataDetailPage/DataDetailPage.tsx
> +            <Heading as="h1">{getPanelTitle(result)}</Heading>
Isn't `Heading` an `h1`, unless specified otherwise?

2020-10-14 11:39 UTC, janjaap commented on src/app/pages/MapPage/detail/DetailDefinitionList.tsx
> +        {/* eslint-disable-next-line no-nested-ternary */}
Nested ternaries are very hard to read. Can you rewrite the block below to something more readable?

2020-10-14 11:39 UTC, janjaap commented on src/app/pages/MapPage/detail/DetailPanel.tsx
> +  <>
No need for a Fragment here

2020-10-14 11:39 UTC, janjaap commented on src/app/pages/MapPage/detail/DetailPanel.tsx
> +      <>
Specify a `key` prop

2020-10-14 11:39 UTC, janjaap commented on src/app/pages/MapPage/detail/DetailPanel.tsx
> +          <DetailHeading styleAs={subItem ? 'h6' : 'h4'}>{item.title}</DetailHeading>
`h6` Is very deeply nested. Does that still result in a semantically correct document?

2020-10-14 11:39 UTC, janjaap commented on src/map/components/detail-result/MapDetailResult.tsx
> +        notification.value ? (
Why not filter `result?.data?.notifications` before mapping? Then this check isn't necessary.

2020-10-14 11:47 UTC, chrisvanmook commented on src/app/pages/DataDetailPage/DataDetailPage.tsx
> +            {!!result?.value?.data?.infoBox && <DetailInfoBox {...result?.value?.data?.infoBox} />}
will remove 👍

2020-10-14 12:32 UTC, chrisvanmook commented on src/app/pages/DataDetailPage/DataDetailPage.tsx
> +            <Heading as="h1">{getPanelTitle(result)}</Heading>
True, attribute can be removed

2020-10-14 12:34 UTC, chrisvanmook commented on src/app/pages/MapPage/detail/DetailPanel.tsx
> +  <>
Thought so too, but then I get this TS error... 
![image](https://user-images.githubusercontent.com/2486227/95989207-3f660d00-0e2a-11eb-83a8-22cc3575970d.png)

I think it does need a Fragment because we iterate and return elements without a parent otherwise

2020-10-14 13:48 UTC, chrisvanmook commented on src/app/pages/DataDetailPage/useDataDetail.ts
> +      if (mapDetail.isAuthorized && !geometry) {
apparently? I basically copy / paste this from a saga so i'd rather leave this in. This whole file can be removed after releasing the new map anyway :)

2020-10-14 13:51 UTC, chrisvanmook commented on src/map/services/map-services.config.ts
> -                  'Medewerkers/ketenpartners van Gemeente Amsterdam kunnen inloggen om kadastrale subjecten te bekijken. Om ook zakelijke rechten van natuurlijke personen te bekijken, moet je als med
They should show up in `PromiseResult`. I've made a ticket in Jira: DI-1204

2020-10-14 14:14 UTC, chrisvanmook commented on src/app/pages/MapPage/detail/DetailPanel.tsx
> +          <DetailHeading styleAs={subItem ? 'h6' : 'h4'}>{item.title}</DetailHeading>
`styleAs` will only give the style of a h6 to the component.

2020-10-14 14:25 UTC, chrisvanmook commented on src/app/pages/MapPage/detail/DetailDefinitionList.tsx
> +        {/* eslint-disable-next-line no-nested-ternary */}
Sure, any preference of how to render it?I think if we do like this, it isn't improving readability much tbh:
```jsx
<DefinitionListItem term={term} key={term}>
          {(() => {
            if (link) {
              return (
                <Link href={link} inList>
                  {description}
                </Link>
              )
            }

            return showMoreShowLess ? (
              <ShowMoreShowLess maxHeight="200px">
                <StyledCustomHTMLBlock body={description} />
              </ShowMoreShowLess>
            ) : (
              description
            )
          })()}
          {alert && <Alert>{alert}</Alert>}
        </DefinitionListItem>
```

2020-10-14 14:28 UTC, chrisvanmook commented on src/app/pages/MapPage/detail/DetailDefinitionList.tsx
> +        {/* eslint-disable-next-line no-nested-ternary */}
Or better like this? 
```jsx
const renderShowMoreShowLess = description && description.length > 300
      const renderLink = link && !renderShowMoreShowLess
      const renderDescription = !link && !renderShowMoreShowLess
      return (
        <DefinitionListItem term={term} key={term}>
          {renderShowMoreShowLess && (
            <ShowMoreShowLess maxHeight="200px">
              <StyledCustomHTMLBlock body={description} />
            </ShowMoreShowLess>
          )}
          {renderLink && (
            <Link href={link} inList>
              {description}
            </Link>
          )}
          {renderDescription && description}
          {alert && <Alert>{alert}</Alert>}
        </DefinitionListItem>
```

2020-10-14 14:30 UTC, chrisvanmook commented on src/app/pages/MapPage/detail/DetailDefinitionList.tsx
> +        {/* eslint-disable-next-line no-nested-ternary */}
https://github.com/Amsterdam/atlas/pull/3428/commits/7236e6cde5f477a2ea173f091af7f5634753429b

2020-10-14 14:41 UTC, jonkoops requested changes
Going to leave a partial review now so some comments can be addressed.

2020-10-14 14:41 UTC, jonkoops commented on src/app/pages/MapPage/detail/DetailDefinitionList.tsx
> +  entries?: DetailResultItemDefinitionListEntry[]
Should we not make this mandatory and prevent empty values from being passed instead? I don't see why anyone would want a list with no entries. If we want to keep this around let's not render the `DefinitionList` at all:

```tsx
const DetailDefinitionList: FunctionComponent<DetailDefinitionListProps> = ({ entries }) => {
  if (!entries) {
    return null
  }

  return (
    <DefinitionList />
  )
}
```

2020-10-14 14:41 UTC, jonkoops commented on src/app/pages/MapPage/detail/DetailLinkList.tsx
> +  return item.links?.length ? (
Should we not assume that links are always present and handle possibly empty values upstream?

2020-10-14 14:41 UTC, jonkoops commented on src/map/types/details.ts
> -// TODO: Drop 'DetailResultItemDefault' in favor of 'DetailResultItemDefinitionList'
Nice that we can finally drop this one.

2020-10-14 14:41 UTC, jonkoops commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +type Coordinate = [number, number]
Instead of using this type we could also use the `Position` type from the `geojson` package.

2020-10-14 14:41 UTC, jonkoops commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +  if (location.length !== 2) {
This check does not reflect the actual type of `Coordinate`, either `Coordinate` needs to be updated to reflect all possible types (e.g. `Position` from the `geojson` package), or this check should be removed.

2020-10-14 14:41 UTC, jonkoops commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +  let rdLocation
Instead of defining these values here and giving them a value later on, why not initialize them here directly?

```suggestion
  const wgs84Location = type === 'WGS84' ? location : rdToWgs84({
    x: rdLocation[0],
    y: rdLocation[1],
  })

  const rdLocation = type === 'RD' ? location : wgs84ToRd({
    lat: wgs84Location[0],
    lng: wgs84Location[1],
  })
```

2020-10-14 14:41 UTC, jonkoops commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +  const formattedWgs84Location = Object.values(wgs84Location)
`Object.values` has no guarantee that the order remains the same, in this regard it is the same as a for in loop according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in):

> A `for...in` loop iterates over the properties of an object in an arbitrary order (see the delete operator for more on why one cannot depend on the seeming orderliness of iteration, at least in a cross-browser setting).

This means that it cannot be used for this instance where the order of the coordinates is relevant.

2020-10-14 14:41 UTC, jonkoops commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +  let rdLocation
`wgs84Location` and `rdLocation` are untyped and the value is polymorphic (both an array of numbers or an object with specific properties). A type should be added here.

2020-10-15 09:25 UTC, chrisvanmook commented on src/app/components/PromiseTemplate/PromiseResult.tsx
> +  if (result.error instanceof AuthError && result.error.code === 401) {
I think that's a good idea, I've created a new ticket DI-1221

2020-10-15 09:26 UTC, chrisvanmook commented on src/app/components/PromiseTemplate/PromiseResult.tsx
> +  window.location.reload()
Nice one, thanks!

2020-10-15 09:30 UTC, janjaap commented on src/app/components/PromiseTemplate/PromiseResult.tsx
> +  window.location.reload()
Since we're using react router, we can use the `useHistory` hook and call 
```jsx
const history = useHistory()
history.go(0)
```
I think 😬

2020-10-15 09:31 UTC, chrisvanmook commented on src/app/pages/MapPage/detail/DetailDefinitionList.tsx
> +  entries?: DetailResultItemDefinitionListEntry[]
Thanks I've updated this

2020-10-15 10:06 UTC, chrisvanmook commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +  if (location.length !== 2) {
For now I'll leave this in, as we are not sure if we'll actually get a location of type `Position`. It's moved from angular code...

2020-10-15 10:11 UTC, chrisvanmook commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +  let rdLocation
Nice one, was brainlessly copy pasting from old angular junk

2020-10-15 10:13 UTC, chrisvanmook commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +  const formattedWgs84Location = Object.values(wgs84Location)
Wow didn't knew this. Will make it a string literal instead

2020-10-15 10:14 UTC, chrisvanmook commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +  let rdLocation
It's typed now when applying your suggestion from earlier

2020-10-15 10:17 UTC, chrisvanmook commented on src/shared/services/coordinate-reference-system/convertCoordinates.ts
> +function convertCoordinates(location: Coordinate, type: 'RD' | 'WGS84') {
Changed

2020-10-16 14:37 UTC, jonkoops approved these changes

2020-10-16 14:41 UTC, merged