[DI-1109] Bouwdossier linklist fix
Amsterdam/atlas pull request #3491
Opened 2020-10-22 15:32 UTC by janjaap

This PR fixes a issue where, on bouwdossier pages, a list of (seemingly) duplicates links were shown. The cause of this was that, from the API output, both `nummeraanduiding` results and `verblijfsobject` results were rendered as links to corresponding pages. After making some enquiries at the GOB-team, they advised not to show the `nummeraanduiding` results, because those are subject to change and cannot be referenced as 'address'.

In addition, this PR adds a fixture for the output of the `bouwdossier` endpoint of the `iiif-metadata` API.

2020-10-23 13:38 UTC, jonkoops requested changes

2020-10-23 13:38 UTC, jonkoops commented on test/withAppContext.js
> +const withAppContext = (Component) => (
Can we add the correct type information to this method?

2020-10-23 13:38 UTC, jonkoops commented on src/normalizations/construction-files/getAddresses.ts
> +  type: 'verblijfsobject'
Are we sure this is the only possible type?

2020-10-23 13:38 UTC, jonkoops commented on src/normalizations/construction-files/getAddresses.ts
> +const getAddresses = (results: Adressen[]): AddressResult[] =>
The return type can be inferred here.

2020-10-23 13:38 UTC, jonkoops commented on src/app/components/Gallery/Gallery.tsx
> +const Gallery: React.FC<GalleryProps> = ({ allFiles, id, access, ...rest }) => {
Conventionally we can `...rest` `...otherProps` in a lot of our code.

2020-10-23 13:38 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +const ConstructionFileDetail: FunctionComponent<Bouwdossier> = ({
It's a bit weird we are passing all these props individually instead of just passing one prop in that contains all the data. This is existing code so there is not much we can do about it but it seems like this could be improved in the future.

2020-10-23 13:38 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Status = 'Aanvraag' | 'Behandeling' | null
It might be better to make the `null` overload part of the definition of the field inside the interface, this way this type can be re-used by other interfaces without inheriting the nullability.

2020-10-23 13:38 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Status = 'Aanvraag' | 'Behandeling' | null
Since these fields are only used in `Bouwdossier` we could name them `BouwdossierAccess` and `BouwdossierStatus` since they are not really re-uasable. Inlining would also be an option, but this is all a stylistic choice.

2020-10-23 13:38 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +export type Bouwdossier = {
If you feel up for it it would be nice to move all this type information to the `api` directory as per file structure there. This would also mean moving the fetching logic from `ConstuctionFilesPage` in the same directory. Take a look at the existing code there it will give you a good idea of the structure and how these things are put together.

2020-10-23 13:38 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +        .sort((a, b) => a.subdossier_titel.localeCompare(b.subdossier_titel))
This sorting logic might potentially be expensive to do, should we memoize this value?

2020-10-26 07:27 UTC, janjaap commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Status = 'Aanvraag' | 'Behandeling' | null
How would I do that?

2020-10-26 08:41 UTC, chrisvanmook commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Status = 'Aanvraag' | 'Behandeling' | null
Also would probably make an enum?

2020-10-26 08:41 UTC, chrisvanmook commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Bestanden = {
This is a generic problem in our codebase: the use of Dutch and English in code is very random and is driving me crazy 😛  We should make guidelines on how and when we are using Dutch and English (Like `Bouwdossier` vs. `ConstructionFile`). Let's create an issue where we can discuss this, document (ADR?) and have something to refer to. 

In this case for `Bestanden` I think we could use `File` instead, but again, might be something we should discuss first. Also note the type in this case is supposed to be singular, not plural.

2020-10-26 08:41 UTC, chrisvanmook commented on src/normalizations/construction-files/getAddresses.test.ts
> +  it('returns a sorted list of objects', () => {
Think we should return a sorted list of addresses (instead of just objects), right?

2020-10-26 08:41 UTC, chrisvanmook commented on test/fixtures/iiif-metadata_bouwdossier.json
> +{
Bit nit-picky here, but isn't this supposed to be a mock, not a fixture?

2020-10-26 09:10 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Status = 'Aanvraag' | 'Behandeling' | null
@janjaap remove the `null` here and change `dossier_status?: Status` to `dossier_status?: Status | null` :)

2020-10-26 09:13 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Bestanden = {
I do agree generally, but I would make an exception for the `api` directory as we're trying to map as closely to the terminology of the actual API.

2020-10-26 12:58 UTC, janjaap commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Bestanden = {
I do agree with Jon on this one; we shouldn't try to translate properties from an API endpoint. This will be confusing and make debugging/understanding the code base a lot more difficult.

2020-10-26 12:59 UTC, janjaap commented on test/fixtures/iiif-metadata_bouwdossier.json
> +{
We're mocking the API response with data coming from a fixture.

2020-10-26 13:09 UTC, chrisvanmook commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +type Bestanden = {
Good point, lets only change it to `Bestand` then

2020-10-26 13:33 UTC, jonkoops requested changes

2020-10-26 13:33 UTC, jonkoops commented on src/api/iiif-metadata/bouwdossier/getBouwdossier.ts
> +export const getBouwdossier = async (id: string) =>
Can we rename this method to `getBouwdossierById`? We're already doing this for some other API methods.

2020-10-26 13:33 UTC, jonkoops commented on src/api/iiif-metadata/bouwdossier/getBouwdossier.ts
> +export const getBouwdossier = async (id: string) =>
Just realized since we're not awaiting anything in this method and a promise is returned directly this method does not have to be `async`. Same goes for some of the existing API methods we already have.

2020-10-26 13:33 UTC, jonkoops commented on src/api/iiif-metadata/bouwdossier/getBouwdossier.ts
> +  fetchWithToken<Bouwdossier>(joinUrl([environment.API_ROOT, 'iiif-metadata', 'bouwdossier', id]))
If you want you could already combine some of the parts of the path that are known. For example.
```suggestion
  fetchWithToken<Bouwdossier>(joinUrl([environment.API_ROOT, 'iiif-metadata/bouwdossier', id]))
```

2020-10-26 13:33 UTC, jonkoops commented on src/api/iiif-metadata/bouwdossier/types.ts
> +export type Bestanden = {
Can we use the singular form here for the type name? Same goes for the other types in this file.

2020-10-26 13:33 UTC, jonkoops commented on src/api/iiif-metadata/bouwdossier/types.ts
> +  activiteiten: any[]
Is there a reason why we have `any` here?

2020-10-26 13:33 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.test.tsx
> +// convert JSON data to JSON data so that the typescript compiler can parse it (not doing so will show a warning on the use of string literal types)
Instead of doing this why not put the raw data in a `.ts` file so it can infer the types directly?

2020-10-26 13:33 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +import { Bouwdossier as BouwdossierType } from '../../../api/iiif-metadata/bouwdossier'
Why create an alias called `BouwdossierType` here? It looks like it doesn't cause any naming conflicts.

2020-10-26 13:33 UTC, jonkoops commented on src/app/pages/ConstructionFilesPage/ConstructionFilesPage.tsx
> +  Bouwdossier as BouwdossierType,
Also here you could use `Bouwdossier` directly without creating an alias.

2020-10-26 13:33 UTC, jonkoops commented on src/app/pages/ConstructionFilesPage/ConstructionFilesPage.tsx
> +    setResults(bouwdossierResult.value)
The advantage of using `usePromise` is that you already have the value, so there is no need to keep more state around. It also makes it easy the different states.

It might be a good idea to use `PageTemplate` as well, which allows you to delegate these states such as loading, error to a generic component. For a good example of this check out `ActualityPage`.

2020-10-26 13:51 UTC, janjaap commented on src/normalizations/construction-files/getAddresses.ts
> +  type: 'verblijfsobject'
According to the GOB-team, yes. We shouldn't be using nummeraanduidingen.

2020-10-26 14:19 UTC, janjaap commented on src/api/iiif-metadata/bouwdossier/getBouwdossier.ts
> +  fetchWithToken<Bouwdossier>(joinUrl([environment.API_ROOT, 'iiif-metadata', 'bouwdossier', id]))
What's the difference?

2020-10-26 14:51 UTC, janjaap commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +export type Bouwdossier = {
Done. Moves types to a separate API folder

2020-10-26 14:52 UTC, janjaap commented on src/api/iiif-metadata/bouwdossier/types.ts
> +  activiteiten: any[]
The type could not be determined. I looked up what the expected type is in the API's repo. Changed it.

2020-10-26 14:53 UTC, janjaap commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.test.tsx
> +// convert JSON data to JSON data so that the typescript compiler can parse it (not doing so will show a warning on the use of string literal types)
Good suggestion. I fixed it by exporting the fixture by casting it to an explicit type.

2020-10-26 14:54 UTC, janjaap commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +import { Bouwdossier as BouwdossierType } from '../../../api/iiif-metadata/bouwdossier'
It's not clear from the `import` statement that we're importing a type, that's why I renamed it here

2020-10-26 15:18 UTC, janjaap commented on src/app/pages/ConstructionFilesPage/ConstructionFilesPage.tsx
> +    setResults(bouwdossierResult.value)
Let's save that for another PR

2020-10-26 15:44 UTC, jonkoops commented on src/api/iiif-metadata/bouwdossier/getBouwdossier.ts
> +  fetchWithToken<Bouwdossier>(joinUrl([environment.API_ROOT, 'iiif-metadata', 'bouwdossier', id]))
Stylistic, but doesn't matter either way.

2020-10-26 15:45 UTC, jonkoops commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +import { Bouwdossier as BouwdossierType } from '../../../api/iiif-metadata/bouwdossier'
Understandable however we do not do this unless we have conflicting names already in scope. Could you change this?

2020-10-26 15:47 UTC, janjaap commented on src/app/components/ConstructionFileDetail/ConstructionFileDetail.tsx
> +import { Bouwdossier as BouwdossierType } from '../../../api/iiif-metadata/bouwdossier'
Done

2020-10-26 15:56 UTC, jonkoops approved these changes

2020-10-26 15:58 UTC, merged