[DI-1154] Zoek redirect fix
Amsterdam/atlas pull request #3524
Opened 2020-10-28 07:46 UTC by janjaap

This PR fixes an issue where a redirect wasn't working any more. The cause of this was that a utility function expected an API request to return with a specific prop. The API endpoint was changed and the new output didn't have the expected prop.

In order to fix it, the proposed changes:
- add fixtures and an API entrypoint function to the API `v1/bag/nummeraanduiding` folder.
  Note the folder structure; the Amsterdam API contains more than one `nummeraanduiding` endpoint of which we use two: `/bag/v1.1/nummeraanduiding` and `/v1/bag/nummeraanduiding`. The former uses an unsupported naming structure and will be phased out at some point. The latter uses the official (yet not officially released and apparently still in beta 🤯 ) structure.
- add `nummeraanduiding` types for the `/v1/bag/nummeraanduiding` endpoint
- add sufficient tests

2020-10-28 10:26 UTC, alimpens commented on src/app/redirects.js
> +      window.setTimeout(() => window.location.replace(redirectTo), 0)
Why do you use a timeout of zero seconds here? Doesn't that break this hack?

2020-10-28 10:26 UTC, alimpens commented on src/app/redirects.test.js
> +    // no-op
This is a bit opaque. Maybe define why catch shouldn't do anything?

2020-10-28 10:37 UTC, janjaap commented on src/app/redirects.js
> +      window.setTimeout(() => window.location.replace(redirectTo), 0)
The whole point of the `setTimeout` call is to delay the `window.location.replace` call. There is no need to delay it with 1000 milliseconds; the code should be executed when all other code has been executed and then a delay of 0 ms is enough since the execution is moved from the execution stack to the event loop.

2020-10-28 10:38 UTC, janjaap commented on src/app/redirects.test.js
> +    // no-op
This was existing code. I didn't look into why a `try/catch` block is necessary here.

2020-10-28 10:44 UTC, alimpens commented on src/app/redirects.test.js
> +    // no-op
I think the empty catch is to `hide unexpected async errors from Jest`, right? That's a bit more descriptive than `no-op`

2020-10-28 10:45 UTC, janjaap commented on src/app/redirects.test.js
> +    // no-op
It's pretty clear that an empty `catch` does that; the comment doesn't add anything we don't already know.

2020-10-28 10:55 UTC, alimpens commented on src/app/redirects.test.js
> +    // no-op
I disagree, I think the original comment makes it obvious that we're intentionally not showing something. `no-op` just means nothing is happening there.

2020-11-02 10:16 UTC, jonkoops requested changes

2020-11-02 10:16 UTC, jonkoops commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> + * @param {String} queryParams - Full URL or search string
There is no need to annotate the type here as we already get this information from TypeScript.

2020-11-02 10:16 UTC, jonkoops commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  return fetchWithoutToken(`${url}?${searchParams.toString()}`)
If you do not want to do string concatenation I believe you could also use the `URL` constructor here. 
```suggestion
  const url = new URL(joinUrl([environment.API_ROOT, 'v1/bag/nummeraanduiding']))
  
  url.search  = searchParams.toString()

  return fetchWithoutToken(url.toString())
```

2020-11-02 10:16 UTC, jonkoops commented on src/app/utils/getVerblijfsobjectIdFromAddressQuery.ts
> + * @param {String} locationSearch - Full URL or search string
No need to add the type here as well, this will be taken care of by TypeScript.

2020-11-02 10:16 UTC, jonkoops commented on src/app/utils/getVerblijfsobjectIdFromAddressQuery.ts
> +  if (totalElements !== 1) return ''
Instead of checking the `totalElements` it would be more safe to check for the value of `data.nummeraanduiding[0]` directly. Unfortunately TypeScript will always return a non-undefined type from array accessors but that of course does not mean the value returned cannot be undefined.

2020-11-02 10:25 UTC, janjaap commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  if (!searchParams.get('postcode') || !searchParams.get('huisnummer')) {
Could do that, but then it will pass for `&postcode=&huisnummer=` in the URL, because `.has()` will return true for an empty string.

2020-11-02 10:26 UTC, janjaap commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> + * @param {String} queryParams - Full URL or search string
I know, but I added the docblock so that I could mention that the function can expect either a full url or just the search string. That is not something that can be deducted from the type

2020-11-02 10:28 UTC, janjaap commented on src/app/utils/getVerblijfsobjectIdFromAddressQuery.ts
> + * @param {String} locationSearch - Full URL or search string
Again true, but I wanted to indicate that the function can receive both a full url as well as a search string

2020-11-02 10:30 UTC, janjaap commented on src/app/utils/getVerblijfsobjectIdFromAddressQuery.ts
> +  if (totalElements !== 1) return ''
Not entirely true, because the function needs to return a value only when the total amount equals 1. I can check for the value of the first element in the result, but I still need to ensure that there is only one element.

2020-11-02 10:31 UTC, janjaap commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  return fetchWithoutToken(`${url}?${searchParams.toString()}`)
I don't see a benefit with the proposed change.

2020-11-02 10:31 UTC, janjaap commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  const paramsString = queryParams.substr(queryParams.indexOf('?'))
`queryParams` Can be either a full url or just a search string

2020-11-02 10:35 UTC, jonkoops commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  const paramsString = queryParams.substr(queryParams.indexOf('?'))
Then this point is indeed moot.

2020-11-02 10:35 UTC, jonkoops commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  if (!searchParams.get('postcode') || !searchParams.get('huisnummer')) {
Ah, yes. That makes sense :+1:

2020-11-02 10:37 UTC, jonkoops commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> + * @param {String} queryParams - Full URL or search string
True, but you can write the same docs without the type as follows:

```
@param queryParams - Full URL or search string
```

This will work also. I actually thought we had a linting rule for this but it might only be on other repos.

2020-11-02 10:38 UTC, jonkoops commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  return fetchWithoutToken(`${url}?${searchParams.toString()}`)
The benefit is that you are leaving *all* the parsing and formatting logic for URLs to the built-in classes that are provided by the browser.

2020-11-02 10:38 UTC, jonkoops commented on src/app/utils/getVerblijfsobjectIdFromAddressQuery.ts
> + * @param {String} locationSearch - Full URL or search string
Same as the previous one, you can omit the type and keep the rest :smile:

2020-11-02 10:39 UTC, jonkoops commented on src/app/utils/getVerblijfsobjectIdFromAddressQuery.ts
> +  if (totalElements !== 1) return ''
Ah I was not aware of this logic, then this code makes sense :+1:

2020-11-02 10:41 UTC, jonkoops requested changes

2020-11-02 10:41 UTC, jonkoops commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +    return null
Looks like the build is failing since this is not a `Promise<null>`. You can either mark this method as `async` or return `Promise.resolve(null)` here.

2020-11-02 11:01 UTC, janjaap commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  return fetchWithoutToken(`${url}?${searchParams.toString()}`)
In your example, search param parsing happens twice, because of `searchParams.toString()` and setting the result of that to `url.search`. I'm not inclined to apply the proposed change here.

2020-11-02 11:49 UTC, jonkoops approved these changes

2020-11-02 11:51 UTC, jonkoops commented on src/api/v1/bag/nummeraanduiding/getNummeraanduidingByAddress.ts
> +  return fetchWithoutToken(`${url}?${searchParams.toString()}`)
It's not that important, either way is fine. Parsing should not occur twice per-se, that all depends on the internal API of `URL`. Besides that, it's not like we're calling this method on any budget so it doesn't really matter if it was parsed multiple times.

2020-11-02 12:17 UTC, merged