(Chore) Fetch proxy
Amsterdam/atlas pull request #3552
Opened 2020-11-02 15:16 UTC by janjaap

This PR adds a function to the API service that will automatically append authentication headers to requests. This will (in an upcoming PR) replace alll `fetchWithToken` and `fetchWithoutToken` calls.

2020-11-03 12:25 UTC, jonkoops requested changes

2020-11-03 12:25 UTC, jonkoops commented on src/shared/services/api/api.test.js
> +import { createUrlWithToken, fetchWithToken, fetchProxy } from './api'
Can we turn this into a TypeScript file while we are at it?

2020-11-03 12:25 UTC, jonkoops commented on src/shared/services/api/api.ts
> +    .then((response) => handleErrors(response, reloadOnUnauthorized))
As far as I can tell the `reloadOnUnauthorized` flag is never used anywhere, let's remove all instances of it from this file (including the other methods).

2020-11-03 12:25 UTC, jonkoops commented on src/shared/services/api/api.ts
> +export const fetchProxy = <T = any>(
Why the name `fetchProxy`? What is this method proxying?

2020-11-03 12:25 UTC, jonkoops commented on src/shared/services/api/api.ts
> +}
I'd like to see this be as close as possible to the existing Fetch API, let's extend the existing `RequestInit` interface here and add the functionality we want to use to make our lives easier. For example:

```ts
interface FetchOptions extends RequestInit {
  searchParams?: UrlParams
}
```

Then inside of the method where we use this interface we can do:

```ts
function fetch(url: string, options?: FetchOptions) {
  const { searchParams, ...fetchOptions } = options ?? {}
  const fullUrl = new URL(url)

  fullUrl.search = new URLSearchParams(searchParams).toString()

  return fetch(fullUrl.toString(),  fetchOptions)
}
```

2020-11-03 12:25 UTC, jonkoops commented on src/shared/services/api/api.ts
> +    method: 'GET',
`GET` is the default, no need to specify it.

2020-11-03 12:48 UTC, janjaap commented on src/shared/services/api/api.ts
> +export const fetchProxy = <T = any>(
Well, `fetch` was already taken and I needed a name. In essence, this function proxies the global `fetch` function, but I'm open to changing it if you have a better suggestion.

2020-11-03 12:54 UTC, janjaap commented on src/shared/services/api/api.ts
> +    .then((response) => handleErrors(response, reloadOnUnauthorized))
There is one function that sets `reloadOnUnauthorized` to true; `geosearch` in `/shared/services/search`

2020-11-03 14:12 UTC, jonkoops commented on src/shared/services/api/api.ts
> +export const fetchProxy = <T = any>(
I actually do not have any better suggestions, just wondering as to the motivation. Let's leave it like this, we can always rename it in the future.

2020-11-03 14:17 UTC, jonkoops commented on src/shared/services/api/api.ts
> +    .then((response) => handleErrors(response, reloadOnUnauthorized))
Let's remove the one from `fetchProxy` only then, I think that kind of stuff should be handled upstream.

2020-11-04 10:18 UTC, janjaap commented on src/shared/services/api/api.ts
> +export const fetchProxy = <T = any>(
I'm also not too happy with the name, but it was the best I could think of.

2020-11-04 13:21 UTC, jonkoops approved these changes
Looks good to me!

2020-11-04 13:21 UTC, jonkoops commented on src/shared/services/api/api.ts
> +      ...requestHeaders,
Are you sure we can spread this `Headers` object like this? Does it implement `Iterable`?

2020-11-04 13:21 UTC, jonkoops commented on src/shared/services/api/api.ts
> +const handleErrors = (response: Response, reloadOnUnauthorized: boolean = false) => {
When providing a default value it is not needed to specify the type as it can be inferred.

```suggestion
const handleErrors = (response: Response, reloadOnUnauthorized = false) => {
```

2020-11-05 07:32 UTC, janjaap commented on src/shared/services/api/api.ts
> +      ...requestHeaders,
Good point. Not possible indeed. Applied a different way of merging the headers.

2020-11-05 10:40 UTC, jonkoops approved these changes

2020-11-06 12:15 UTC, merged