(Chore) Docker cleanup
Amsterdam/atlas pull request #3599
Opened 2020-11-09 10:17 UTC by janjaap

The changes in this PR make it easier to set up the application locally, with Docker. 
It:
- reorders commands in the Dockerfile for faster building; putting files that are less likely to change higher up in the command stack
- expands the `.dockerignore` list so that Docker won't include unnecessary files in the build context
-  adds a `docker-compose.yml` file as well as a `Makefile`
- updates the Nginx configuration so that, when the apps runs in http, assets from `fast.fonts.net` will be downloadable
- allows both `debugger` and `console` statements to be left in the production bundle, when the environment variable `DEBUG` has been set with the value 'true'

2020-11-10 14:46 UTC, jonkoops requested changes

2020-11-10 14:46 UTC, jonkoops commented on .dockerignore
> +.dependabot
Instead of keeping this file up to date like this perhaps we can ignore all files and include only the ones we need. See: https://kevinpollet.dev/posts/how-to-use-your-dockerignore-as-a-whitelist/

2020-11-10 14:46 UTC, jonkoops commented on Dockerfile
> +COPY package.json package-lock.json /app/
Since the workdir is already the `/app` directory can we just copy these directly?

```suggestion
COPY package.json package-lock.json .
```

2020-11-10 14:46 UTC, jonkoops commented on Dockerfile
> +    npm cache clean --force
Why do we want to run a cache clean here?

2020-11-10 14:46 UTC, jonkoops commented on Dockerfile
> +    .browserslistrc \
I don't believe we are actually using the `browserslistrc` file as we're passing this information in the Webpack config manually but I could be wrong.

2020-11-10 14:46 UTC, jonkoops commented on Dockerfile
>      /app/
Same here, the workdir is still `/app` so I think we can just copy the files to the current directory.

2020-11-10 14:46 UTC, jonkoops commented on Dockerfile
> +COPY test /app/test
Same here, the workdir is still `/app` so I think we can just copy the files to the current directory.

2020-11-10 14:46 UTC, jonkoops commented on Dockerfile
> +RUN echo "build ${BUILD_NUMBER} - `date`" > ./dist/version.txt
`BUILD_NUMBER` gets passed in for sure?

2020-11-10 14:46 UTC, jonkoops commented on Dockerfile
> +# Deploy
This is not really a deployment.

2020-11-10 14:46 UTC, jonkoops commented on nginx.conf
> +      font-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.amsterdam.nl fast.fonts.net;
Should we also remove the protocol of other entries in this file? Are we sure we are still only allowing HTTPS as a protocol by removing it?

2020-11-10 14:46 UTC, jonkoops commented on webpack.prod.ts
> +            keep_fnames: debugMode,
Should these two flags not be handled by the sourcemapping in the browser?

2020-11-10 14:46 UTC, jonkoops commented on Makefile
> +# show help by default
I personally never use makefiles, what is the added advantage of this vs. just using the Docker Compose CLI tools?

2020-11-10 15:18 UTC, janjaap commented on Dockerfile
> +    npm cache clean --force
Because we need to keep the intermediate containers as small as possible and therefore we need to remove anything that we don't need in production.

2020-11-10 15:19 UTC, janjaap commented on Dockerfile
> +RUN echo "build ${BUILD_NUMBER} - `date`" > ./dist/version.txt
No, doesn't look like it: https://data.amsterdam.nl/version.txt.
I'll remove it.

2020-11-10 15:20 UTC, janjaap commented on nginx.conf
> +      font-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.amsterdam.nl fast.fonts.net;
I removed it, because the local Docker setup runs in http instead of https and leaving this in will throw warnings. We might be able to circumvent this by settings specific flags in Chrome. I'll have a look.

2020-11-10 15:22 UTC, janjaap commented on Makefile
> +# show help by default
It acts as a proxy so that you don't have to remember any Docker-related commands. Also, when the setup gets more complex (for whatever reason), we can move complexity into the Makefile.
A Makefile is also a way to extract logic and complexity when running in, for instance, Jenkins; it's easier to issue commands from there instead of having to resort to Groovy or DSL.

2020-11-10 15:23 UTC, janjaap commented on Dockerfile
> +# Deploy
That image is deployed, not the one above.

2020-11-10 15:59 UTC, janjaap commented on Dockerfile
> +    .browserslistrc \
The file is read by Webpack; removing it will prevent the application from building

2020-11-10 16:05 UTC, janjaap commented on nginx.conf
> +      font-src 'self' 'unsafe-inline' 'unsafe-eval' https://static.amsterdam.nl fast.fonts.net;
Because the local environment runs on http, requests will go to `//fast.fonts.net` which equals to `http://fast.fonts.net`. Removing the schema allows requests to either http or https.

2020-11-11 09:34 UTC, jonkoops approved these changes

2020-11-11 10:39 UTC, chrisvanmook approved these changes

2020-11-11 10:40 UTC, merged