[DI-1333] service worker
Amsterdam/atlas pull request #3634
Opened 2020-11-17 16:40 UTC by janjaap

This PR implements caching strategies for assets loaded in the `atlas` application. For the service worker to work correctly, this PR:
- lets Webpack inject the necessary chunk references in the public HTML file
- loads a service worker only when on production
- transpiles chunks without hashes in their file names; the service worker already takes care of versioning
- removes cache groups configuration from Webpack production configuration; this allows Webpack to determine for itself which chunks need to be generated and, subsequently, which can be added to or removed from the cache when a page reload occurs
- defines specific caching strategies for assets that are retrieved from all subdomains that the `atlas` application queries. Each subdomain has its own caching lifetime, based on the nature of the asset that is served from a subdomain (images can be cached for a longer period than JSON responses should be, for instance)

2020-11-19 10:35 UTC, chrisvanmook approved these changes

2020-11-19 10:42 UTC, janjaap commented on src/store/store.js
> +// import '../shared/ducks/error/error-message'
Ah, yes. I came across those and I was wondering what they were doing there. After looking into it, I noticed that those modules only have default or named exports and don't execute any code, but I wasn't entirely sure. Do you know, perhaps?

2020-11-19 17:26 UTC, jonkoops requested changes

2020-11-19 17:26 UTC, jonkoops commented on webpack.common.ts
> +        chunkFilename: '[name].css',
Would this not cache the CSS file forever? Since the name will always be the same, even if the contents have changed.

2020-11-19 17:26 UTC, jonkoops commented on webpack.dev.ts
> +        watchContentBase: true,
Why do we need to watch the build result in `dist`?

2020-11-19 17:26 UTC, jonkoops commented on src/store/store.js
> +// import '../shared/ducks/error/error-message'
Yeah looks weird, especially the `queryParameters` which seems to register new paramaters on onother module.

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> -const CHUNKS = {
Good to see this gone.

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> +export default [createConfig({ legacy: false, mode: 'production', singleBuild: true })].map(
Are we only doing non-legacy builds now? Perhaps we should first pick up the story to remove legacy browser support.

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> +        filename: '[name].js',
Why are we only using `name` here? Now our assets are no longer fingerprinted and this might cause the wrong code to load.

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> +                drop_debugger: !debugMode,
I think we have a linting rule to prevent debugger statements from showing up. This could be removed IMHO.

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> +        nodeEnv: 'production',
This will default to the `mode` argument, which is set to `production`, this line can be removed.

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> +        namedModules: true,
These options have been removed in future versions of WebPack, let's not introduce them here. See: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#changes-to-the-structure

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> +        chunkIds: 'named',
According to the WebPack documentation:
> The `deterministic` option is useful for long term caching, but still results in smaller bundles compared to `hashed`
- https://webpack.js.org/configuration/optimization/#optimizationmoduleids

Since this is the production build should we not be using this option instead?

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> +        splitChunks: {
Would the default config not be enough here? See: https://webpack.js.org/plugins/split-chunks-plugin/#optimizationsplitchunks

2020-11-19 17:26 UTC, jonkoops commented on webpack.prod.ts
> +          mode: debugMode ? 'development' : 'production',
Could you explain this 'debug' mode? Why not simply use the existing mode we already provide to Webpack?

2020-11-19 17:34 UTC, jonkoops commented
I would also be nice if we could inform the user when they loaded an older version of the site and a new one is available. Something much like this: https://deanhume.com/displaying-a-new-version-available-progressive-web-app/

2020-11-19 17:40 UTC, chrisvanmook commented
I'm going to check this out and test this thoroughly tomorrow or monday

2020-11-20 06:25 UTC, janjaap commented on index.ejs
> -    <% for (let key in htmlWebpackPlugin.options.modernScripts) { %>
Because Webpack injects the async scripts itself.

2020-11-20 06:26 UTC, janjaap commented on webpack.dev.ts
> +        watchContentBase: true,
This settings means that changes to files in the project's root folder, and not only the `src` folder, will trigger a compilation.

2020-11-20 06:29 UTC, janjaap commented on webpack.prod.ts
> +                drop_debugger: !debugMode,
I added this, because it's handy to have debugger statements in production code when running the application in Docker locally. By default, debugger statements are removed from the production bundle, but not when the env var `DEBUG` has been set.

2020-11-20 06:40 UTC, janjaap commented on webpack.prod.ts
> +        chunkIds: 'named',
That's an option that's only available in Webpack. We're still using 4.

2020-11-20 06:41 UTC, janjaap commented on webpack.prod.ts
> +          mode: debugMode ? 'development' : 'production',
Because the existing mode for the Webpack production configuration is always 'production'. When working on the service worker configuration, it's useful to not have a minified version of that service worker. The value 'development', used here, can be anything, as long as it isn't 'production'.

2020-11-20 06:43 UTC, janjaap commented on webpack.prod.ts
> +        namedModules: true,
They're still valid Webpack 4 options.

2020-11-20 07:49 UTC, janjaap commented on src/store/store.js
> +// import './queryParameters'
I'll revert this change; this import definitely does something.

2020-11-20 09:23 UTC, janjaap commented on webpack.common.ts
> +        chunkFilename: '[name].css',
Good one; I removed the hashes from the JS chunks, because the service worker already takes care of hashing those files. I assumed that this was also the case for CSS files, but I'll verify that.

2020-11-20 10:27 UTC, janjaap commented on webpack.common.ts
> +        chunkFilename: '[name].css',
Tested it and the `[name].css` format gets picked up the service worker as expect; changes are applied.

2020-11-20 10:28 UTC, janjaap commented on webpack.prod.ts
> +export default [createConfig({ legacy: false, mode: 'production', singleBuild: true })].map(
Yeah, that is true. Generating two sets of chunks isn't picked up by the service worker. I'll see if I can make it work with both sets.

2020-11-20 10:28 UTC, janjaap commented on webpack.prod.ts
> +        filename: '[name].js',
Service worker takes care of hashing.

2020-11-20 10:45 UTC, janjaap commented on webpack.prod.ts
> +        splitChunks: {
Leaving the prop `splitChunks` out of the settings won't generate any chunks.

2021-01-05 09:59 UTC, jonkoops requested changes

2021-01-05 13:21 UTC, janjaap commented on index.ejs
> +      if ('serviceWorker' in navigator && '${DEPLOY_ENV}' === 'production') {
The value for `DEPLOY_ENV` is 'production' for both the acceptance and production environments, so that case is covered.

2021-01-05 13:26 UTC, janjaap commented on package.json
> +    "prebuild": "rimraf ./dist",
Nice, I'll remove it. Good catch.

2021-01-05 16:59 UTC, jonkoops commented on index.ejs
> +      if ('serviceWorker' in navigator && '${DEPLOY_ENV}' === 'production') {
If I look at the log on the acceptance environment it states it is `acceptance`, so I do not think that the service worker will actually be loaded there:

![image](https://user-images.githubusercontent.com/695720/103674923-9b4eb680-4f7f-11eb-9598-0be890fd23e6.png)

2021-01-05 17:00 UTC, jonkoops commented on src/store/store.js
> +// import './queryParameters'
@janjaap this has been resolved since?

2021-01-06 08:26 UTC, janjaap commented on index.ejs
> +      if ('serviceWorker' in navigator && '${DEPLOY_ENV}' === 'production') {
Ah, yes. I see. I was thrown off by the values that I found in the deploy config in Gitlab. Has been changed.

2021-01-06 11:13 UTC, jonkoops commented on index.ejs
> +      if ('serviceWorker' in navigator && '${DEPLOY_ENV}' === 'production') {
Yeah, this environment variable is a bit silly. I would like to get rid of it at some point.

2021-01-12 08:43 UTC, jonkoops requested changes

2021-01-12 08:43 UTC, jonkoops commented on webpack.prod.ts
>      splitChunks: {
I am still not a fan of this automatic chunking for several reasons:

If I run a test on HTTP/1.1 I can see that a lot of the connections are stalling when I slow down the network in Chrome devtools. The screen-shot below shows the stalling time in gray:

![image](https://user-images.githubusercontent.com/695720/104288332-f28ce380-54b7-11eb-803e-cba464e4dc99.png)

This results in a slower initial page load of about 0.5s on the 'fast 3G' preset in Chrome dev tools.

Compare that to the fatter chunks that can all be downloaded in parallel:

![image](https://user-images.githubusercontent.com/695720/104288680-69c27780-54b8-11eb-84a3-5f345a7c2cb6.png)
 
Perhaps that HTTP/2 could fix this issue, but I would rather not include this change now. Also because it would only increase the surface area of possible missing chunks and thus errors.

2021-01-12 08:43 UTC, jonkoops commented on webpack.prod.ts
> -    chunkFilename: '[name].[contenthash].js',
I would prefer to restore the asset fingerprinting logic in these file names. The reason being is that we now end up with unhashed chunks for small chunks such as the `ArticleDetailPage`:

![image](https://user-images.githubusercontent.com/695720/104290266-6fb95800-54ba-11eb-9eb6-d654adb52034.png)

This might look fine, but I am afraid that we might load a newer `ArticleDetailPage` chunk from an older bundle for the application code, which might cause errors.

2021-01-12 09:32 UTC, jonkoops commented on webpack.prod.ts
> -    chunkFilename: '[name].[contenthash].js',
This point is moot due to SW caching.

2021-01-12 09:36 UTC, jonkoops commented on webpack.prod.ts
>      splitChunks: {
This will be solved by using HTTP/2 in the future.

2021-01-12 09:45 UTC, jonkoops approved these changes

2021-01-12 10:54 UTC, jonkoops approved these changes

2021-01-12 11:40 UTC, merged