[DI-1392] Remove legacy chunks
Amsterdam/atlas pull request #3664
Opened 2020-11-24 13:29 UTC by janjaap

This PR removes the generation of backwards compatible JS chunks.

2020-12-01 11:51 UTC, jonkoops requested changes

2020-12-01 11:51 UTC, jonkoops commented on webpack.common.ts
> -                    ...(!options.legacy
I do not know exactly why I configured this as such but if we want to use ES2015+ methods in browsers that support modules we will still have to include the correct polyfills. It would be best to always set `useBuiltIns` and `corejs` to cover our bases here.

2020-12-01 11:51 UTC, jonkoops commented on webpack.prod.ts
> +            drop_debugger: !debugMode,
We already have a linting rule to make sure that no debugging statements exist in production builds. Can we perhaps drop the `debugMode` entirely?

![image](https://user-images.githubusercontent.com/695720/100733881-219b3a00-33cf-11eb-8312-7c943cbd8110.png)

2020-12-01 11:51 UTC, jonkoops commented on webpack.prod.ts
> +    splitChunks: {
Testing this locally `splitChunks` creates a **lot** of seperate files:
![Screenshot from 2020-12-01 12-20-38](https://user-images.githubusercontent.com/695720/100734931-b6526780-33d0-11eb-9324-236b792d0c95.png)

I think it would be best to use the WebPack defaults here which makes things a lot more manageable:
![Screenshot from 2020-12-01 12-27-26](https://user-images.githubusercontent.com/695720/100735017-d2ee9f80-33d0-11eb-9405-f0aacbac87d5.png)

2020-12-01 11:51 UTC, jonkoops commented on webpack.prod.ts
> +    moduleIds: 'named',
Considering that we want to be able to cache these files based on the file name in which case we would want to use the `deterministic` value as it will not change between compilations, from the [WebPack docs](https://webpack.js.org/configuration/optimization/#optimizationchunkids):

> 'deterministic' - Short numeric ids which will not be changing between compilation. Good for long term caching. Enabled by default for production mode.

The documentation also says the following:

> If the environment is development then optimization.chunkIds is set to 'named', while in production it is set to 'deterministic'

In my opinion we should not provide this value, and instead fall back on the more sensible defaults from WebPack.

2020-12-09 07:24 UTC, janjaap commented on package.json
> +    "prop-types": "15.7.2",
Well, it shouldn't be used in production, so it makes sense to list it as a dev dependency. Just for good measure, because it makes no difference since we're not installing our dependencies with the `--production` option.

2020-12-09 07:36 UTC, janjaap commented on webpack.common.ts
> -                    ...(!options.legacy
Good one, I'll change that.

2020-12-09 07:37 UTC, janjaap commented on webpack.prod.ts
> +            drop_debugger: !debugMode,
The point of `debugMode` is that, when running the application locally with Docker, we can still set debugger statements in the code that aren't removed. This helps with stepping through the production code.

2020-12-09 07:41 UTC, janjaap commented on webpack.prod.ts
> +    splitChunks: {
I don't agree; the Webpack defaults will throw everything in one chunk which is really big. This forces that chunk to be downloaded again with any change to the code. By generating more chunks, the chance of having to re-download a large part of the application on a new release, become a lot smaller and thus adding to the run-time and overall performance of the application.
Browsers can handle up to six requests simultaneously, so having as many smaller chunks sd with the change in this PR, is not an issue.

2020-12-09 07:43 UTC, janjaap commented on webpack.prod.ts
> +    moduleIds: 'named',
`deterministic` Is specific to Webpack 5; we're still using 4. And more importantly, long-term caching will handled by the service worker.

2020-12-09 07:56 UTC, janjaap commented on package.json
> +    "@babel/plugin-proposal-nullish-coalescing-operator": "^7.12.1",
I added those because of errors during testing. I ran the tests and these errors don't pop up anymore 🤔 .

Anywho, I'll remove the deps.

2020-12-09 14:06 UTC, chrisvanmook approved these changes

2020-12-09 14:06 UTC, chrisvanmook commented on .browserslistrc
> -IE 11
🎉

2020-12-09 14:17 UTC, merged