BetaMap: Fixed several bugs in drawtool, changed URl structure and ignore certain redux middleware when on betamap
Amsterdam/atlas pull request #3707
Opened 2020-11-30 14:59 UTC by chrisvanmook

In this PR I've done the following things:
- Make sure "Detail", "Geosearch"and "Panorama" pages follow the same structure as the legacy URL, except instead of beginning with "/data" we use "/kaart" for now, so the legacy pages can still exist
- URLs containing "/kaart" (so if user is on beta map) it will skip certain redux middleware, causing loads of side-effects
- Added a warning to `useParam` hook
- Fixed several bugs regarding the draw-tool

2020-12-01 08:47 UTC, janjaap requested changes

2020-12-01 08:47 UTC, janjaap commented on src/app/components/PanoramaViewer/PanoramaViewerMarker.tsx
> +    click: ({ latlng }) => setLocation && setLocation(latlng),
According to the Leaflet docs, the `latlng` object, has a method `isValid()`. Might be good to check that as well before calling `setLocation`?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/MapControls.tsx
> +          }
Add a test to cover this change?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/MapControls.tsx
> +          }
Same here, add a test?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/MapPage.tsx
>  const MapPage: React.FC = () => {
This component seems quite complex. Can you add a couple of tests to cover its functionality?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/MapPanelContent.tsx
> +      </Switch>
Shouldn't routing be happening at the highest level possible in the application?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/detail/DetailPanel.tsx
> +          }}
Add test cases for these changes?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/detail/buildDetailUrl.ts
> +  // Todo: AfterBeta: this can be removed
Can the whole function body be removed or just line 10?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/draw/DrawResults.tsx
> +        })
Cover with a test case?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/draw/DrawTool.tsx
> +  polygonsRef.current = polygons
Wouldn't this also do the trick?
```jsx
const polygonsRef = useRef(polygons)
```
Instead of creating a ref with a specific value and then setting that value again.

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/draw/DrawTool.tsx
> +    window.localStorage.setItem('polylines', JSON.stringify(shape.polylines))
According to [caniuse.com](https://caniuse.com/namevalue-storage):
> In private browsing mode, Safari and iOS Safari up to including version 10.x as well as the Android browser (not include Chrome for Android) do not support setting sessionStorage or localStorage.
Why is it necessary to store these values in localStorage? Isn't it possible to use the URL params for that, like it is done for a lot of other occasions in the application?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/draw/DrawTool.tsx
> +      }}
Shouldn't pushing a new state to the history be the responsibility of the component that renders the draw tool instead of the draw tool itself?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/draw/DrawTool.tsx
>  const DrawTool: React.FC<DrawToolProps> = ({ setCurrentOverlay }) => {
This component doesn't have any tests. Please increase the coverage on it. There is a lot happening in this component that becomes more understandable by adding tests.

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/map-search/MapSearchMarker.tsx
> +    if (legendLeafletLayers && legendLeafletLayersRef) {
Isn't `legendLeafletLayersRef` always truthy? The call to `useRef` always returns an object.

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/map-search/MapSearchMarker.tsx
> +      .filter((overlay) => !!overlay.layer.detailUrl)
Double negation isn't necessary in case of validating a string for its truthy value

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/map-search/MapSearchResults.tsx
> +        : Promise.reject(),
Please cover this by a test case.

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/map-search/PanoramaPreview.tsx
> +  const newLayers = [...activeLayersWithoutPano, ...PANO_LAYERS]
Shouldn't this value be a `useMemo` value instead of `activeLayersWithoutPano`?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/map-search/PanoramaPreview.tsx
> +    [location],
The removes dependencies are still used. Why is it necessary to remove them from the list?

2020-12-01 08:47 UTC, janjaap commented on src/app/pages/MapPage/map-search/PanoramaPreview.tsx
> +      <PreviewLink forwardedAs={linkComponent} to={to} inList>
Please cover the value of `to` with a test case

2020-12-01 08:47 UTC, janjaap commented on src/app/utils/useParam.ts
> +    }
Shouldn't this throw instead of show a warning? Seems serious enough to break.

2020-12-01 08:47 UTC, janjaap commented on src/store/middleware/addMetaToRoutesMiddleware.js
> +  }
Add a test? If you do, then at least the test will break if this condition is not removed when transitioning from old to new map.

2020-12-01 08:47 UTC, janjaap commented on src/store/middleware/preserveUrlParametersMiddleware.js
> +  }
Same, please add a test

2020-12-01 08:47 UTC, janjaap commented on src/store/middleware/setQueriesFromStateMiddleware.js
> +  }
Add a test, please.

2020-12-01 17:30 UTC, chrisvanmook commented on src/app/components/PanoramaViewer/PanoramaViewerMarker.tsx
> +    click: ({ latlng }) => setLocation && setLocation(latlng),
If I look into the type, only `LatLngBounds` have this. We don't really need to worry here anyway since it's typed

2020-12-01 17:34 UTC, jonkoops requested changes

2020-12-02 12:24 UTC, chrisvanmook commented on src/app/pages/MapPage/MapPanelContent.tsx
> +      </Switch>
Why should that be? I think the whole idea of RR is that you can render components conditionally based on the pathname, not per se on the highest level. In this case our view is the Map, but the content in the sidepanel can vary from "dataselectie", "geozoeken" or "detail-pages".

2020-12-02 13:17 UTC, janjaap commented on src/app/pages/MapPage/MapPanelContent.tsx
> +      </Switch>
For no reason in particular, was just wondering what the approach is in the application.

2020-12-02 13:18 UTC, chrisvanmook commented on src/app/pages/MapPage/detail/buildDetailUrl.ts
> +  // Todo: AfterBeta: this can be removed
just the statement, will update the comment

2020-12-02 13:20 UTC, chrisvanmook commented on src/app/pages/MapPage/draw/DrawTool.tsx
> +  polygonsRef.current = polygons
Thought that would work as well, but unfortunately it didn't... IMO we should find a solution in `react-map` and `ARM` to fix this, like passing a dependency array to every event so it knows when to remove and add the eventlisteners again.

2020-12-02 13:24 UTC, chrisvanmook commented on src/app/pages/MapPage/draw/DrawTool.tsx
> +    window.localStorage.setItem('polylines', JSON.stringify(shape.polylines))
We also store them in the URL, the localstorage is a nice-to-have improvement in case users want to go back to their drawing after closing the tool and search for other stuff

2020-12-02 14:23 UTC, chrisvanmook commented on package.json
> +    "leaflet-draw": "1.0.4",
It will, I'll remove it when this PR is approved. Meanwhile I'll put a label on it

2020-12-02 14:24 UTC, chrisvanmook commented on src/app/utils/buildQueryString.ts
> +  paramsToEmit?: Array<UrlParam<any>>,
Lol haha yes :D

2020-12-03 09:47 UTC, chrisvanmook commented on src/app/components/PanoramaViewer/PanoramaViewer.tsx
> +    [],
`activeLayers` you mean then?

2020-12-03 14:28 UTC, chrisvanmook commented on src/app/pages/MapPage/map-search/MapSearchMarker.tsx
> +    if (legendLeafletLayers && legendLeafletLayersRef) {
Good point! will remove

2020-12-03 14:29 UTC, chrisvanmook commented on src/app/pages/MapPage/draw/DrawTool.tsx
>  const DrawTool: React.FC<DrawToolProps> = ({ setCurrentOverlay }) => {
Regarding the size of this pull-request, I'm going to create another issue in Jira for this.

2020-12-03 14:30 UTC, chrisvanmook commented on src/app/pages/MapPage/map-search/MapSearchMarker.tsx
> +      .filter((overlay) => !!overlay.layer.detailUrl)
indeed! will remove

2020-12-04 12:27 UTC, janjaap commented on src/app/components/PanoramaViewer/PanoramaViewer.test.tsx
> +    })
Would be better to check the value of `window.location`, because that's the result that we're after when pushing a new item on the history stack. Doesn't really matter that we accomplish that by using `react-router-dom` or some other means.

2020-12-04 12:27 UTC, janjaap commented on src/app/pages/MapPage/MapControls.test.tsx
> +    fireEvent.click(openDrawtoolButton)
Assert that `setShowDrawToolMock` hasn't been call prior to clicking the button.

2020-12-04 12:27 UTC, janjaap commented on src/app/pages/MapPage/MapPage.test.tsx
> +}))
Instead of having to rely on `react-router-dom` (we might something else in the future), you can also directly change the value of `window.location`. You'd probably have to make that object writable, like so:

```javascript
  Object.defineProperties(global, {
    location: {
      writable: true,
      value: global.location,
    },
  })

```

2020-12-04 12:27 UTC, janjaap commented on src/map/components/search-results/MapSearchResults.test.jsx
> +
Why is it necessary to mock this module?

2020-12-04 12:34 UTC, janjaap commented on src/app/pages/MapPage/map-search/PanoramaPreview.test.tsx
> +    await waitFor(() => {
Instead of wrapping this, you can also await the finding of an element by testid:
```jsx
await findByTestId('panoramaPreview')
```

2020-12-04 12:34 UTC, janjaap commented on test/fixtures/gebieden/stadsdeel.json
> +{"_links":{"self":{"href":"https://acc.api.data.amsterdam.nl/gebieden/stadsdeel/03630000000018/?format=json"}},"_display":"Centrum (A)","stadsdeelidentificatie":"03630000000018","code":"A","date_modi
Can you move this file to the `src/api/gebieden/stadsdeel` folder? There are already examples in the `src/api` folder. Would also be nice if you can add a `types.ts` and have the fixture exported by that type so that tests can make use of those typings.

2020-12-04 12:34 UTC, janjaap commented on src/app/pages/MapPage/map-search/PanoramaPreview.test.tsx
> +      const link = container.querySelector('a')
You could also have clicked the link and have verified the value of `window.location`, but checking the element's params also does the trick

2020-12-04 12:41 UTC, chrisvanmook commented on src/app/pages/MapPage/map-search/PanoramaPreview.test.tsx
> +    await waitFor(() => {
In this case I want to select the link to the panorama, that doesn't have a testid. So we could either do this or add a data-testid to the link itself

2020-12-04 12:52 UTC, chrisvanmook commented on src/map/components/search-results/MapSearchResults.test.jsx
> +
I've mocked this for now, as I would completely have to refactor this test if I wouldn't. IMO it's not worth the time and effort to do so, as this component (including the mocked hook) will be completely removed after releasing the new Map module

2020-12-04 13:04 UTC, chrisvanmook commented on src/app/pages/MapPage/MapPage.test.tsx
> +}))
I do agree, but I cannot get this to work. If I log `window.location` in the component it show the right value that I've set in the test. However, the value coming from `useLocation` is not equal to that value. No idea why...

2020-12-04 13:06 UTC, chrisvanmook commented on src/app/pages/MapPage/MapControls.test.tsx
> +    fireEvent.click(openDrawtoolButton)
I already do that on line 70 :)

2020-12-04 13:07 UTC, chrisvanmook commented on src/app/components/PanoramaViewer/PanoramaViewer.test.tsx
> +    })
Like said here https://github.com/Amsterdam/atlas/pull/3707#discussion_r536084744, I cannot get this to work for now. Let's discuss this next week :)

2020-12-04 13:12 UTC, chrisvanmook commented on src/app/pages/MapPage/map-search/PanoramaPreview.test.tsx
> +      const link = container.querySelector('a')
Could've done that as well, not really making any difference (IMHO a bit pointless to test the integrity of the router)

2020-12-04 13:31 UTC, chrisvanmook commented on src/app/utils/useParam.ts
> +    }
won't be resolved when remove the dual setup. I think this is the case: it happens when the values from `useParam` are used in a non-react eventhandler, and the value of eg. `setLocation` is still the same (and holds an 'old' value of `location`, coming from `useLocation`), even after a re-render of the component. Happens a lot with leaflet events. We should make a fix for this in the ARM and react-maps repo.

2020-12-04 13:49 UTC, chrisvanmook commented on src/app/pages/MapPage/draw/DrawTool.tsx
> +      }}
Unfortunately we decided to keep the current interaction, which works as follows:
- using the draw measure tool, does not change the location, only updates the parameter in the URL
- using the draw polygon tool, DOES trigger a location change: the user should navigate to so-called 'Dataselection' page (like `/data/bag/adressen`) because the user "selected" an area on the Map.

2020-12-04 15:06 UTC, chrisvanmook commented on src/app/pages/MapPage/map-search/PanoramaPreview.tsx
> +    [location],
Because it's not necessary to update this every time, since it's just a preview of the Panorama. only when the location changes it should update

2020-12-08 12:16 UTC, janjaap commented on src/store/middleware/addMetaToRoutesMiddleware.js
> +  }
In the coverage repo I can see that the branch on line 10 isn't fully covered. Can you have a look?

2020-12-08 12:16 UTC, janjaap commented on src/store/middleware/preserveUrlParametersMiddleware.js
> +  }
The branches on lines 18 and 20 aren't covered by your tests. Can you also have a look there?

2020-12-08 12:16 UTC, janjaap commented on src/api/gebieden/stadsdeel.json
> +{"_links":{"self":{"href":"https://acc.api.data.amsterdam.nl/gebieden/stadsdeel/03630000000018/?format=json"}},"_display":"Centrum (A)","stadsdeelidentificatie":"03630000000018","code":"A","date_modi
Can you add types for this file? This will help catching edge cases in tests.

2020-12-08 13:38 UTC, chrisvanmook commented on src/api/gebieden/stadsdeel/types.ts
> +  date_modified: string
@jonkoops this should be of type `Date`, however in `fixture.ts` it shows `type 'string' is not comparable to type 'Date'. json file`. Any idea how to fix this?

2020-12-08 14:09 UTC, janjaap commented on src/app/pages/MapPage/detail/DetailPanel.test.tsx
> +import stadsdeelResponse from '../../../../api/gebieden/stadsdeel/stadsdeel.json'
If you import from '../../../../api/gebieden/stadsdeel/fixture' you should get typing support

2020-12-08 15:57 UTC, janjaap approved these changes

2020-12-08 16:34 UTC, merged