Replace Redux router links with React router
Amsterdam/atlas pull request #3801
Opened 2021-01-02 16:52 UTC by jonkoops

2021-01-03 13:49 UTC, chrisvanmook approved these changes

2021-01-20 07:07 UTC, janjaap requested changes
There's about twenty other components that make use of `redux-first-router-link`. Will those be tackled in this PR as well?

2021-01-20 07:07 UTC, janjaap commented on src/app/links.ts
> +export const toConstructionFile = (
The name of the functions in this module are confusing; they suggest performing an action, but instead return an object that can be object as the value of the `to` prop on a `Link` component. Maybe `getConstructionFileLocation`?

2021-01-20 07:07 UTC, janjaap commented on src/app/links.test.ts
> +  it('creates a link', () => {
Doesn't create a link, but return location properties that can be used to construct a link from.

2021-01-21 17:55 UTC, jonkoops commented
> There's about twenty other components that make use of `redux-first-router-link`. Will those be tackled in this PR as well?

This was originally the plan, but we decided to split this up into multiple separate tasks so those will come as separate PRs.

2021-01-21 17:58 UTC, jonkoops commented on src/app/pages/MapPage/draw/DrawResults.tsx
> +const TableRouterLink = styled(ReactRouterLink)`
That import cannot be removed yet as it is still used for some code (see line 45-48).

```ts
const ResultLink = styled(RouterLink)`
  width: 100%;
  margin-bottom: ${themeSpacing(2)};
`
```

2021-01-21 17:59 UTC, jonkoops commented on src/app/links.ts
> +export const toConstructionFile = (
I agree that the naming is not fantastic but I think it makes sense in the context it's used. I'd like to keep it like this for now, we can always rename them all at the end.

2021-01-21 18:03 UTC, jonkoops commented on src/app/links.test.ts
> +  it('creates a link', () => {
Changed this to 'location descriptor' like the type it returns.

2021-01-21 18:11 UTC, merged