[DI-1244] jest-fetch-mock replace
Amsterdam/atlas pull request #3851
Opened 2021-01-13 13:54 UTC by janjaap

2021-01-14 11:33 UTC, jonkoops requested changes

2021-01-14 11:33 UTC, jonkoops commented on src/app/components/IIIFThumbnail/IIIFThumbnail.test.tsx
> +import * as fs from 'fs'
I think we can use the default import here:
```suggestion
import path from 'path'
import fs from 'fs'
```

2021-01-14 11:33 UTC, jonkoops commented on src/app/components/IIIFThumbnail/IIIFThumbnail.test.tsx
> +    let request: any
Can we not use the `Request` type here instead?

2021-01-14 11:33 UTC, jonkoops commented on src/app/pages/MapPage/detail/DetailPanel.test.tsx
> +// tests need to be (re)written for this (quite complex) component
When will we do this? Is there a ticket for it?

2021-01-14 11:33 UTC, jonkoops commented on src/shared/services/auth/auth.test.js
> +describe.skip('The auth service', () => {
We're no longer testing this? Is there a ticket to restore this?

2021-01-14 12:27 UTC, janjaap commented on src/app/pages/MapPage/detail/DetailPanel.test.tsx
> +// tests need to be (re)written for this (quite complex) component
Shouldn't that be part of the story you were working on for the detail panels?

2021-01-14 12:27 UTC, janjaap commented on src/shared/services/auth/auth.test.js
> +describe.skip('The auth service', () => {
Working on those tests as we speak; will create a separate PR for that

2021-01-14 15:56 UTC, janjaap commented on src/app/components/IIIFThumbnail/IIIFThumbnail.test.tsx
> +    let request: any
No, we can't. The `msw` dep doesn't have a `@types` package.

2021-01-15 10:27 UTC, jonkoops approved these changes

2021-01-15 10:28 UTC, jonkoops commented on src/app/pages/MapPage/detail/DetailPanel.test.tsx
> +// tests need to be (re)written for this (quite complex) component
Yeah, just a bummer that we need to disable this now.

2021-01-15 10:30 UTC, janjaap commented on src/app/pages/MapPage/detail/DetailPanel.test.tsx
> +// tests need to be (re)written for this (quite complex) component
Meh, there was only one test case in this suite and that even didn't test much 🤷🏻‍♂️

2021-01-15 10:31 UTC, merged