WIP remove svg-loader
Amsterdam/atlas pull request #3854
Opened 2021-01-14 14:33 UTC by chrisvanmook

2021-01-21 08:42 UTC, janjaap requested changes

2021-01-21 08:42 UTC, janjaap commented on src/app/components/ActiveFilters/ActiveFilters.tsx
> +            title={`Filter verwijderen: ${label}: ${option}`}
A `title` attribute shouldn't be on an element like this if the text content of that element is the same. See https://www.a11yproject.com/posts/2013-04-22-title-attributes/#:~:text=HTML%20title%20attributes%20are%20often,and%20possibly%20not%20even%20used. for reference

2021-01-21 08:42 UTC, janjaap commented on src/app/components/DataSelection/DataSelectionFilters.tsx
>                        <li className="c-data-selection-available-filters__item">
`<li>` Element should have a `key` prop

2021-01-21 08:42 UTC, janjaap commented on src/app/components/DataSelection/DataSelectionList/DataSelectionList.tsx
> +                  key={i}
Why not use the value of `variables`?

2021-01-21 08:42 UTC, janjaap commented on src/app/components/DataSelection/DataSelectionSbiFilters.tsx
> +                    title={option.label}
`title` Prop should not be on this element

2021-01-21 08:42 UTC, janjaap commented on src/app/components/DataSelection/DataSelectionSbiFilters.tsx
>                  <li className={`c-sbi-filter__item c-sbi-filter__item--${option.slug}`}>
`<li>` Element should have a `key` prop

2021-01-21 08:42 UTC, janjaap commented on src/app/components/SplitScreen/SplitScreen.tsx
> +      <div style={{ width: '100%' }}>{rightComponent}</div>
Make it into a styled component. Using object literals as prop values has a negative impact on rendering performance.

2021-01-21 08:42 UTC, janjaap commented on src/map/components/detail-result/MapDetailResultWrapper.test.jsx
> +    expect(wrapper.find('map-detail-result__header').length).toBe(0)
Shouldn't 'map-detail-result__header' be '.map-detail-result__header'?

2021-01-21 08:42 UTC, janjaap commented on src/map/components/detail-result/MapDetailResultWrapper.tsx
>              title="Volledig weergeven"
No `title` attribute

2021-01-21 08:42 UTC, janjaap commented on src/map/components/search-results/MapSearchResults.jsx
>                title="Volledig weergeven"
No `title` attribute

2021-01-21 08:42 UTC, janjaap commented on src/map/components/shape-summary/ShapeSummary.tsx
> +      title="Lijn verwijderen"
Should have an attribute `aria-labelledby` and no `title` attribute

2021-01-21 08:42 UTC, janjaap commented on src/map/components/toggle-drawing/ToggleDrawing.jsx
> +  const embedPreviewMode = useSelector(isEmbedPreview)
Using three `useSelector` calls will update and rerender the component three times. Can't these be combined into a single call?

2021-01-21 08:42 UTC, janjaap commented on src/map/containers/panel/_map-panel.scss
> +    //font-size: 32px !important;
Remove?

2021-01-21 08:42 UTC, janjaap commented on src/shared/assets/icons/first.svg
> +            <polygon id="Fill-3" points="6 20 9.00954085 20 9.00954085 6 6 6"></polygon>
`id` Attributes should not be present in `<svg />`, unless explicitly required. Having more than one svg element on a page can lead to duplicate ids, which is invalid HTML. See, for instance, src/shared/assets/icons/last.svg.

2021-01-21 08:42 UTC, janjaap commented on src/shared/assets/icons/maximize.svg
> +            <polygon id="Fill-3" fill="#000000" points="14.9043822 4.61495219 14.9043822 6.5585559 17.9837667 6.5585559 15.3560789 9.22346595 16.7312892 10.5986762 19.4293974 7.86032774 19.4293974 11
Same applies here; duplicate id values

2021-01-21 10:42 UTC, chrisvanmook commented on src/map/components/toggle-drawing/ToggleDrawing.jsx
> +  const embedPreviewMode = useSelector(isEmbedPreview)
Tested this and it's just being rendered once. How do you think this would cause multiple re-renders? Using multiple hooks doesn't re-render a component, unless the hook has side-effects and updates a state.

2021-01-21 11:21 UTC, chrisvanmook commented on src/app/components/ActiveFilters/ActiveFilters.tsx
> +            title={`Filter verwijderen: ${label}: ${option}`}
The text content isn't the same here: I've added `Filter verwijderen`. I shall change it to `aria-label`

2021-01-21 11:21 UTC, chrisvanmook commented on src/map/components/shape-summary/ShapeSummary.tsx
> +      title="Lijn verwijderen"
Don't you mean `aria-label`?

2021-01-21 12:11 UTC, janjaap commented on src/map/components/shape-summary/ShapeSummary.tsx
> +      title="Lijn verwijderen"
No `aria-labelledby`. The value should be an id of a label that contains text that describes the purpose of the button. The label can, or probably should, be hidden from non-screen readers

2021-01-21 12:12 UTC, janjaap commented on src/map/components/toggle-drawing/ToggleDrawing.jsx
> +  const embedPreviewMode = useSelector(isEmbedPreview)
When the component renders first, a call to `useSelector` returns the default selector value. When the store has updated, the selector is called again and then returns the value it should return. The component is then rendered again. So, for three `useSelector` calls, there will be multiple rerenders. Maybe it's not a problem for this particular component, but it can be an expensive operation.

2021-01-21 12:28 UTC, janjaap approved these changes

2021-01-25 16:08 UTC, jonkoops requested changes

2021-01-25 16:08 UTC, jonkoops commented on src/map/components/toggle-drawing/ToggleDrawing.tsx
> +    <>
I think we can drop this fragment, the value returned is a single element.

2021-01-25 16:12 UTC, chrisvanmook commented on src/app/components/DataSelection/DataSelectionList/DataSelectionList.tsx
> +export const toDetailPage = (endpoint: string): LocationDescriptor => {
Will have a look!

2021-01-25 16:13 UTC, chrisvanmook commented on src/environment.ts
> +  GRAPHQL_ENDPOINT: 'http://localhost:8080/cms_search/graphql/',
Whoop yeah no...

2021-01-25 16:13 UTC, jonkoops commented on src/map/components/toggle-drawing/ToggleDrawing.jsx
> +  const embedPreviewMode = useSelector(isEmbedPreview)
I thought that React batches these changes so it doesn't run it unnecessarily.

2021-01-26 07:36 UTC, janjaap commented on src/app/components/DataSelection/DataSelectionList/DataSelectionList.tsx
> +  return (
There is an eslint rule for that, you know.

2021-01-26 10:41 UTC, jonkoops commented on src/app/components/DataSelection/DataSelectionList/DataSelectionList.tsx
> +  return (
> There is an eslint rule for that, you know.

I feel like we should perhaps create a ticket to set up the linting correctly? 😂

2021-01-26 12:57 UTC, jonkoops approved these changes

2021-01-26 14:32 UTC, merged