[DI2-102] Mobile header link fix
Amsterdam/atlas pull request #3873
Opened 2021-01-20 10:24 UTC by janjaap

2021-01-20 12:49 UTC, jonkoops requested changes

2021-01-20 12:49 UTC, jonkoops commented on src/app/components/SearchBar/SearchBar.tsx
>  const StyledSearchBarToggle = styled(SearchBarToggle)`
You should be  able to add the type information here so you don't have to redefine it below.
```suggestion
const StyledSearchBarToggle = styled(SearchBarToggle)<{ searchIsVisible: boolean }>`
```

2021-01-20 12:49 UTC, jonkoops commented on src/app/components/SearchBar/SearchBar.tsx
> +  ${({ searchIsVisible }: { searchIsVisible: boolean }) =>
So this could be removed
```suggestion
  ${({ searchIsVisible }) =>
```

2021-01-20 12:49 UTC, jonkoops commented on src/app/components/SearchBar/SearchBar.tsx
> +  const toggleWidth = (isOpen: boolean): void => {
No need to add `: void` here as the type can be inferred.`
```suggestion
  const toggleWidth = (isOpen: boolean) => {
```

2021-01-20 12:49 UTC, jonkoops commented on src/header/components/HeaderSearch.tsx
> +  )
I believe you can get rid of this `@ts-ignore`:

```suggestion
   if (document.activeElement instanceof HTMLElement) {
     document.activeElement.blur()
   }
```

2021-01-20 12:49 UTC, jonkoops commented on src/header/components/HeaderSearch.tsx
> +        )
Can't we put this hash directly into the constructor?
```suggestion
        const query = new URLSearchParams({
          term: inputValue.trim(),
        })
```

2021-01-20 13:29 UTC, janjaap commented on src/header/components/HeaderSearch.tsx
> +        )
Possibly, but that code was already in the component.

2021-01-20 16:25 UTC, jonkoops commented on src/header/components/HeaderSearch.tsx
> +        )
Sure, but no harm leaving things better than they were before, no?

2021-01-20 16:33 UTC, janjaap commented on src/header/components/HeaderSearch.tsx
> +        )
Very true. But making a change like that requires adding tests, which there are none for this component. I'll create a different PR for that.

2021-01-20 16:49 UTC, jonkoops approved these changes

2021-01-20 17:09 UTC, jonkoops commented on src/header/components/HeaderSearch.tsx
> +        )
I've simplified the code and tested it locally, looks like it was just redundant.

2021-01-21 08:54 UTC, chrisvanmook approved these changes

2021-01-21 09:02 UTC, merged