[DI2-119] Publication date fix
Amsterdam/atlas pull request #3941
Opened 2021-02-09 07:02 UTC by janjaap

This PR fixes an issue where an article's publication date wouldn't be shown correctly. The cause of this was that the code wasn't using the value of `field_publication_day` which rendered the date always with day 1.

In order to fix the issue, the tests for `useNormalizedCMSResults.js` have been rewritten and the file has been refactored by moving functionality out of the main function so it can be tested separately. The functionality slightly changed in that passing in a value for `field_publication_year` and none for `field_publication_month` will show the year (instead of throwing an error). Passing in a value for both `field_publication_year` and `field_publication_month` will always show 1-{month}-{year}.

2021-02-09 16:25 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const year = parseInt(field_publication_year, 10)
I've created a ticket to see if we can get this as a number straight from the Drupal API.

2021-02-09 16:56 UTC, jonkoops requested changes

2021-02-09 16:56 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const yearIsValidNumber = Number.isNaN(year) === false
Would negating this boolean not be shorter?

```suggestion
  const yearIsValidNumber = !Number.isNaN(year)
```

2021-02-09 16:56 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  ].filter(Boolean)
Since months are zero indexed in JavaScript dates would this not lead to a missing month number for January? If `monthIndex` is 1 (so January) and `monthIndex - 1` (so `0`) is passed to the `Boolean` filter will this not result in it getting filtered out?

In this case I think a procedural approach here might be more clear and less error prone:

```suggestion
  const dateParts = [year]
  
  if (!Number.isNaN(monthIndex)) {
    dateParts.push(monthIndex - 1)
  }
  
  // Also check if the month was pushed before, we don't
  // want to accidentally add a day in the month position.
  if (dateParts.length === 2 && !Number.isNaN(day)) {
    dateParts.push(day)
  }
```

2021-02-09 16:56 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const localeDate = new Date(Date.UTC(...dateParts))
Why do we need to run this through as a UTC date? Do we end up on the wrong day in local time when formatting this later otherwise?

2021-02-09 16:56 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.test.js
> +      const field_publication_date = '2020-12-02T16:00:00+01:00'
I noticed that there was the following line to normalize the `field_publication_date` field:

```ts
field_publication_date.replace(' ', 'T')
```

It doesn't look like this string replacement logic is actually used according to the tests. so can it be removed?

2021-02-09 16:57 UTC, janjaap commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const yearIsValidNumber = Number.isNaN(year) === false
Definitely shorter, but not necessarily more readable.

2021-02-09 16:58 UTC, janjaap commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  ].filter(Boolean)
Good one; I'll add a test case for that.

2021-02-09 16:59 UTC, janjaap commented on src/normalizations/cms/useNormalizedCMSResults.test.js
> +      const field_publication_date = '2020-12-02T16:00:00+01:00'
I'm not sure why it is in place; it was already in the code. Might be required, might also not be. Must be there for a reason, so I'd rather leave it in.

2021-02-09 16:59 UTC, janjaap commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const localeDate = new Date(Date.UTC(...dateParts))
I don't know; was already in the code.

2021-02-09 17:12 UTC, janjaap commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  ].filter(Boolean)
Solved it in a different way; a bit cleaner than adding conditions imho

2021-02-09 17:13 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const yearIsValidNumber = Number.isNaN(year) === false
It's being used in other parts of the code like this already though (see the `dateParts` variable).

2021-02-09 17:14 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const localeDate = new Date(Date.UTC(...dateParts))
Fair enough, this is probably fine.

2021-02-09 17:15 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.test.js
> +      const field_publication_date = '2020-12-02T16:00:00+01:00'
If that is the case can we add a test for this scenario as well? Just to cover our asses in case we do some refactoring on this code.

2021-02-09 17:19 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  ].filter(Boolean)
Nice, long as we cover this edge case I am happy :smile:

2021-02-10 07:09 UTC, janjaap commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const localeDate = new Date(Date.UTC(...dateParts))
If we only have a single value, for instance `new Date(2021)`, the value is considered to be a timestamp and will return the wrong date. Using `new Date(Date.UTC(2021))` will solve that.

2021-02-10 07:10 UTC, janjaap commented on src/normalizations/cms/useNormalizedCMSResults.test.js
> +      const field_publication_date = '2020-12-02T16:00:00+01:00'
Tested it and removed the `replace` function; the `Date` constructor is able to deal with either `2019-07-22T11:31:48+00:00` or `2019-07-22 11:31:48+00:00`

2021-02-10 09:34 UTC, jonkoops commented on src/normalizations/cms/useNormalizedCMSResults.js
> +  const localeDate = new Date(Date.UTC(...dateParts))
Ahhhh, yes that makes sense. I guess we could also use `Date.parse` for that.

2021-02-10 09:35 UTC, jonkoops approved these changes

2021-02-10 09:37 UTC, merged