Chore increase coverage
Amsterdam/atlas pull request #3988
Opened 2021-02-15 13:29 UTC by janjaap

This PR:
- fixes an inaccurate check for the `is-object` utility function (and adds tests)
- adds tests for the `getGeometry` function
- converts the touched files to TS

2021-02-15 15:13 UTC, jonkoops requested changes

2021-02-15 15:13 UTC, jonkoops commented on src/shared/services/geometry/geometry.ts
> +interface GeometryContainer {
This type seems to overlap with the type `ApiAddress` defined in `src/map/types/details.ts`. Perhaps we can use that one instead?

2021-02-15 15:13 UTC, jonkoops commented on src/shared/services/geometry/geometry.ts
> +  bezoekadres?: GeometryContainer
This field is also present in the `PotentialApiResult` type defined in `src/map/types/details.ts`. Perhaps we can use that one instead?

2021-02-15 15:13 UTC, jonkoops commented on src/shared/services/geometry/geometry.ts
> +export const isVestigingAmsterdam = (geometrie: Point) => {
`isVestigingAmsterdam` seems to be used only in this file, looks like it does not have to be exported.

2021-02-15 15:13 UTC, jonkoops commented on src/app/components/DataSelection/DataSelectionDownloadButton.tsx
> +  if (geometryFilter?.markers !== undefined) {
Nice cleanup, gotta love optional chaining :partying_face:

2021-02-15 15:13 UTC, jonkoops commented on src/shared/services/geometry/geometry.test.ts
> +
Thanks for writing these tests, it makes it so much clearer what is happening here. :+1:

2021-02-15 15:13 UTC, jonkoops commented on src/shared/services/geometry/geometry.test.ts
> +  it('returns geometry from monumentcoordinaten when bezoekadres is out of bounds', () => {
Does this cover all possible types of 'out of bounds' that could occur?

2021-02-15 15:25 UTC, janjaap commented on src/shared/services/is-object.test.ts
>      expect(isObject({ foo: 'bar' })).toBe(true)
`expect(isObject(Object.create(null))).toBe(true)` Will actually be `null` so the assertion is `false`. But I see you point and I'll add a couple more cases.

2021-02-15 15:26 UTC, janjaap commented on src/shared/services/is-object.test.ts
> +    expect(isObject([])).toBe(false)
Because that is not the intention of the `isObject` function. `null` Is also an object, but not the expected object.

2021-02-15 15:34 UTC, jonkoops commented on src/shared/services/is-object.test.ts
> +    expect(isObject([])).toBe(false)
Perhaps `isPlainObject` or something like that would be better then? To detect a 'POJO' basically.

2021-02-16 07:54 UTC, janjaap commented on src/shared/services/geometry/geometry.ts
> +interface GeometryContainer {
Whoah, good catch. I've replaced it.

2021-02-16 07:56 UTC, janjaap commented on src/shared/services/geometry/geometry.test.ts
> +  it('returns geometry from monumentcoordinaten when bezoekadres is out of bounds', () => {
It doesn't really matter, because it's the return value that matters. And I suspect that the piece of code this test covers, isn't used anywhere.

2021-02-16 07:57 UTC, janjaap commented on src/shared/services/is-object.ts
> +const isObject = (value: any) => value?.constructor?.name === 'Object'
The compiler complained about `value is object` and suggested this:
```typescript
const isObject = (value: any): value is Record<string, unknown> =>
  value?.constructor?.name === 'Object'
```

2021-02-16 08:02 UTC, janjaap commented on src/shared/services/is-object.test.ts
> +    expect(isObject([])).toBe(false)
Actually, there is no way to deduct from the code that the intended return value should be false when evaluating an array as input, so I'll add that.

2021-02-16 12:20 UTC, jonkoops commented on src/app/utils/isObject.test.ts
> +    expect(isObject(Object.create(null))).toBe(false)
This should be `true` instead, an object without a prototype is still an object.

```suggestion
    expect(isObject(Object.create(null))).toBe(true)
```

2021-02-16 12:20 UTC, jonkoops commented on src/app/utils/isObject.ts
> +  Array.isArray(value) || value?.constructor?.name === 'Object'
This type assertion is incorrect, since we are also checking if the value is an array it could also return an `Array` type. A more correct type would be:

```suggestion
const isObject = (value: any): value is Record<string, unknown> | Array<unknown> =>
  Array.isArray(value) || value?.constructor?.name === 'Object'
```

I would still highly recommended changing this back to `object` and remove the array logic entirely. The reason is that with this type the compiler cannot discriminate the primitive, which means the returned value becomes a union. See for example the `getGeometry` method:

![image](https://user-images.githubusercontent.com/695720/108061290-604ca200-7058-11eb-9bdf-209b1d329b5c.png)

Changing the implementation to purely asserting the `object` primitive allows the type to be discriminated properly:

```suggestion
const isObject = (value: any): value is object => value !== null && typeof value === 'object'
```

![image](https://user-images.githubusercontent.com/695720/108061683-f41e6e00-7058-11eb-8e54-7d5d49640e66.png)

2021-02-16 12:20 UTC, jonkoops commented on src/shared/services/is-object.ts
> +const isObject = (value: any) => value?.constructor?.name === 'Object'
Looks like a linting error to me, which is a good rule, but in this case it makes no sense.

2021-02-16 13:00 UTC, jonkoops commented on src/shared/services/is-object.ts
> +const isObject = (value: any) => value?.constructor?.name === 'Object'
Looks like the linter complaints about this, not the compiler. It's a good rule, but for this type discrimination it's not really applicable.

2021-02-22 06:51 UTC, janjaap commented on src/app/utils/isObject.test.ts
> +    expect(isObject(Object.create(null))).toBe(false)
Changed the condition back to the original and adjusted the tests accordingly

2021-02-22 06:51 UTC, janjaap commented on src/app/utils/isObject.ts
> +  Array.isArray(value) || value?.constructor?.name === 'Object'
Reverted to the original implementation

2021-02-22 13:36 UTC, jonkoops commented on src/shared/services/is-object.ts
> +const isObject = (value: any) => value?.constructor?.name === 'Object'
Updated this so types can be correctly inferred.

2021-02-22 13:39 UTC, jonkoops approved these changes

2021-02-22 13:43 UTC, merged