Refactored DataSelection page beta map
Amsterdam/atlas pull request #4122
Opened 2021-04-27 12:45 UTC by chrisvanmook

2021-04-27 13:09 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/DataSelectionProvider.tsx
> -import { useStateRef } from '@amsterdam/arm-core'
Dayum, that is one hell of a cleanup

2021-04-27 13:18 UTC, jonkoops requested changes

2021-04-27 13:18 UTC, jonkoops commented on src/app/components/Alerts/GeneralErrorAlert.tsx
> +import React from 'react'
There is no need to import React anymore since we're using the new JSX transformation that no longer requires it.

2021-04-27 13:18 UTC, jonkoops commented on src/app/components/Alerts/GeneralErrorAlert.tsx
> +  <Alert level="error" data-testid="errorMessage">
`data-testid`, but no test. Can we add a simple test to see if this component renders?

2021-04-27 13:18 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/DataSelectionContext.ts
> -  fetchData: (
Nice cleanup again!

2021-04-27 13:18 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/normalize.ts
> +import { v4 as uuidv4 } from 'uuid'
Can we add some tests for this file?

2021-04-27 13:18 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/normalize.ts
> +// eslint-disable-next-line import/prefer-default-export
I think you can remove this comment, since there are more than one exports in the file.

2021-04-27 13:18 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/normalize.ts
> +  data: any,
Do we have a more specific type we can use here?

2021-04-27 13:18 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/DrawTool.tsx
> +      // const latLngs = layer.getLatLngs() as LatLng[][]
Stray comment here

2021-04-27 13:18 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/DrawMapVisualization.tsx
> +    if (polygon) {
You can use an early return here to reduce the nesting.

```ts
if (!polygon) {
  return null
}
```

2021-04-27 13:18 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/DataSelectionSelectBox.tsx
> +import React, { useCallback } from 'react'
No need to import react here.

2021-04-27 13:18 UTC, jonkoops commented on src/app/pages/MapPage/components/DrawTool/DataSelectionSelectBox.tsx
> +const DataSelectionSelectBox = () => {
Can we add some tests for this file?

2021-04-28 13:24 UTC, chrisvanmook commented on src/app/components/Alerts/GeneralErrorAlert.tsx
> +  <Alert level="error" data-testid="errorMessage">
We already have tests that will render this component and check if it exists in the DOM, so it's covered

2021-04-29 10:43 UTC, jonkoops approved these changes

2021-04-30 08:14 UTC, merged